language: android

sudo: false

jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - android-27
    - build-tools-27.0.3
   
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - "${TRAVIS_BUILD_DIR}/gradle/caches/"
  - "${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

install:
  - touch /home/travis/.android/repositories.cfg
  - echo yes | ${ANDROID_HOME}/tools/bin/sdkmanager "platforms;android-27"

script:
  - ./gradlew build --stacktrace

after_success:
  - bash scripts/prep-key.sh
  - bash upload-apk.sh
